### ISSUE TITLE
TP ended

### ISSUE THREAD

**Issue by YoannLth** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-1-lathuiliere_montes#2]
@Slashgear

**Comment by Slashgear** [comment]
⚠️ package en minuscule

👎 Les instance of c'est pas terrible non ?

❓ La priorité de la multiplication sur l'addtion et la soustraction ça marche ?

👍 Sinon c'est good, c'est bien mieux que la fin de la première itération du TP1

**Comment by YoannLth** [comment]
@Slashgear 

- ⚠️ package en minuscule
Il me semble que tout est déjà en minuscule, sauf le "arithmeticExpression", que j'ai changé en "arithmetic.expression".
<img width="639" alt="capture d ecran 2017-04-02 a 22 15 57" src="https://cloud.githubusercontent.com/assets/15812546/24604051/963f9116-1863-11e7-831d-8fe690a405d8.png">

- 👎 Les instance of c'est pas terrible non ?
Nous avions hésité entre ce traitement et faire une méthode "visiterMultiplication" dans l'interface visiteur. Après réflexion, nous avons réalisé que le traitement des multiplications et des additions diffère seulement dans le cas du visiteur pour calculer. Utiliser des instanceof nous permet ainsi d'éviter la duplication le code.

Si besoin, nous pouvons changer notre structure et créer une méthode "visiterMultiplication" et "visiterAddition" à la place de "visitBinaryOperator". A moins que vous voyiez une autre alternative?

-❓ La priorité de la multiplication sur l'addtion et la soustraction ça marche ?
La gestion de la priorité ce fait par rapport à la hiérarchie de l'arbre. Ci dessous un petit screen avec le parcours infixe, qui montre avec les parenthèses, comment sera effectué le calcul. On voit en dessous, le résultat de l'opération : 3.
<img width="238" alt="capture d ecran 2017-04-03 a 11 50 53" src="https://cloud.githubusercontent.com/assets/15812546/24604299/8c52b7a4-1864-11e7-839b-16970edf4143.png">

Nous n'avons pas défini de règle par rapport à la priorité. Tout ce fait avec la notion de fils droit et fils gauche. Est-ce la le fonctionnement attendu? 🤔

**Comment by Slashgear** [comment]
👍 Les packages

❓ Les instanceof, je me dis, si mon fonctionnel évolue qu'est ce qui sera le plus chiant. (Par exemple si on rajoute une opération) je pense qu'ajouter des méthodes serait mieux (c'est mon avis)

Rien ne t'empêche de faire une méthode privée dans ton visteur qui va te servir d'utilitaire pour éviter la duplication de code.

👍 Pour la priorité de la multiplication sur les autres opérations, c'était juste pour vous poussez à réfléchir au problème. Mais ça me va. Je vous avais dit, je vous note pas la dessus.

**Comment by YoannLth** [comment]
❓ Les instanceof
Dans un soucis d'évolution, alors oui je l'avoue 😅 c'est mieux de distinguer les multiplications et les additions. Je change ça ASAP

**Comment by YannickMontes** [comment]
Done pour les instanceof :) 
C'est plus propre de faire effectivement un traitement pour chaque spécification d'opération binaire. 
On a essayé de garder néanmoins certains morceaux de code qu'on avait fait, en rendant la précédente fonction private (visitBinaryOperator) dans certains visiteurs, qui est appelé dans les fonctions ou le comportement ne change pas :) 

Je penses que c'est plutôt bon, sauf si vous voyez autre chose?

**Comment by Slashgear** [comment]
👍
